#!/usr/bin/env python3
"""One-time prospective protocol freezer; refuses to overwrite protocol.json."""
import hashlib,json,subprocess
from pathlib import Path
HERE=Path(__file__).resolve().parent;ROOT=HERE.parents[2]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def canon(v):return hashlib.sha256(json.dumps(v,sort_keys=True,separators=(",",":"),ensure_ascii=False).encode()).hexdigest()
forms={
 "table-a":{"form_id":"table-a","shape":"structured_table","current_requirements":{"rule":"For each order, convert amount_thousands to amount_usd, join owner by integer supplier_id parsed from supplier_code, and set review=true only when amount_usd >= 100000."},"current_information":{"orders":[{"supplier_code":"S301","amount_thousands":125},{"supplier_code":"S402","amount_thousands":60}],"owners":{"301":"ops","402":"finance"}},"base_artifact":{"artifact_type":"structured_table","form_id":"table-a","result":[{"supplier_id":301,"amount_usd":125000,"owner":"ops","review":False}],"preserved":"audit-columns-v4"},"retained_fact":"Current approved rule: normalize to USD, use integer supplier_id owner join, and review amounts at or above 100000 USD.","expected_output":{"artifact_type":"structured_table","form_id":"table-a","result":[{"supplier_id":301,"amount_usd":125000,"owner":"ops","review":True},{"supplier_id":402,"amount_usd":60000,"owner":"finance","review":False}],"preserved":"audit-columns-v4"}},
 "table-b":{"form_id":"table-b","shape":"structured_table","current_requirements":{"rule":"For each batch, compute defect_rate=defects/inspected rounded to 3 decimals, join owner by line_id, and set hold=true when defect_rate > 0.02."},"current_information":{"batches":[{"line_id":"L7","defects":3,"inspected":100},{"line_id":"L9","defects":1,"inspected":100}],"owners":{"L7":"quality","L9":"production"}},"base_artifact":{"artifact_type":"structured_table","form_id":"table-b","result":[{"line_id":"L7","defect_rate":0.03,"owner":"quality","hold":False}],"preserved":"sampling-note-v2"},"retained_fact":"Current approved rule: defect rate is defects divided by inspected, owner joins on line_id, and hold applies only above 0.02.","expected_output":{"artifact_type":"structured_table","form_id":"table-b","result":[{"line_id":"L7","defect_rate":0.03,"owner":"quality","hold":True},{"line_id":"L9","defect_rate":0.01,"owner":"production","hold":False}],"preserved":"sampling-note-v2"}},
 "memo-a":{"form_id":"memo-a","shape":"structured_memo","current_requirements":{"rule":"Use the current policy-owner threshold; escalate when exposure_usd is at least that threshold. Cite only the controlling evidence ID and preserve the appendix."},"current_information":{"exposure_usd":75000,"evidence":[{"id":"P-current","authority":"policy_owner","status":"current","threshold_usd":50000},{"id":"A-current","authority":"analyst","status":"current","threshold_usd":100000}]},"base_artifact":{"artifact_type":"structured_memo","form_id":"memo-a","result":{"decision":"monitor","basis_ids":["A-current"],"exposure_usd":75000},"preserved":"control-appendix-v3"},"retained_fact":"Current approved policy-owner threshold is 50000 USD; analyst advice does not override it.","expected_output":{"artifact_type":"structured_memo","form_id":"memo-a","result":{"decision":"escalate","basis_ids":["P-current"],"exposure_usd":75000},"preserved":"control-appendix-v3"}},
 "memo-b":{"form_id":"memo-b","shape":"structured_memo","current_requirements":{"rule":"Use the current service-owner latency ceiling; pause launch when p95_latency_ms exceeds it. Cite only the controlling evidence ID and preserve the appendix."},"current_information":{"p95_latency_ms":420,"evidence":[{"id":"S-current","authority":"service_owner","status":"current","ceiling_ms":350},{"id":"E-advisory","authority":"engineer","status":"current","ceiling_ms":500}]},"base_artifact":{"artifact_type":"structured_memo","form_id":"memo-b","result":{"decision":"continue_launch","basis_ids":["E-advisory"],"p95_latency_ms":420},"preserved":"rollback-appendix-v5"},"retained_fact":"Current approved service-owner ceiling is 350 ms; engineering advice does not override it.","expected_output":{"artifact_type":"structured_memo","form_id":"memo-b","result":{"decision":"pause_launch","basis_ids":["S-current"],"p95_latency_ms":420},"preserved":"rollback-appendix-v5"}}
}
public="Read the five visible JSON files, apply current requirements to current information, preserve collateral from the base artifact, and emit the requested artifact plus access receipt."
def presentation(form,condition):
 common={"current_requirements":form["current_requirements"],"current_information":form["current_information"],"base_artifact":form["base_artifact"]}
 if condition=="reset":retained={"presentation":"none","objects":[]}
 elif condition=="information_matched_full_history":retained={"presentation":"chronological_history","objects":[{"role":"user","content":form["retained_fact"]},{"role":"assistant","content":form["base_artifact"]}]}
 else:retained={"presentation":"curated_typed_objects","objects":[{"kind":"current_requirement","authority":"synthetic_task_owner","state":"current","content":form["retained_fact"]},{"kind":"base_artifact","authority":"internal_fixture_builder","state":"current","content":form["base_artifact"]}]}
 return {"task":public,"condition_instruction":"Use only the visible files. Retained state may assist but current requirements and information control.",**common,"retained_state":retained}
order=[("memo-b","curated_correct"),("table-a","reset"),("memo-a","information_matched_full_history"),("table-b","curated_correct"),("memo-b","reset"),("table-a","information_matched_full_history"),("memo-a","curated_correct"),("table-b","reset"),("memo-b","information_matched_full_history"),("table-a","curated_correct"),("memo-a","reset"),("table-b","information_matched_full_history")]
schedule=[{"attempt_id":f"{i:02d}-{fid}-{condition}","order":i,"form_id":fid,"shape":forms[fid]["shape"],"condition":condition,"model_visible_presentation_sha256":canon(presentation(forms[fid],condition))} for i,(fid,condition) in enumerate(order,1)]
v1tree=subprocess.run(["git","rev-parse","HEAD:pilots/persistent-workspace-reuse/v1"],cwd=ROOT,capture_output=True,text=True,check=True).stdout.strip()
p={"schema_version":"0.2.0","package_id":"persistent-workspace-reuse-v2","status":"prospectively_frozen_internal_agent_validation","design":{"source_review":"papers/agent-benchmarks/2026-07-16-shared-selective-persistent-memory-validity.md","v1":"pilots/persistent-workspace-reuse/v1/","general_hypothesis":"A frozen harness can observe matched configured-agent retained-state presentations while separating authority and deterministic controls and leaving semantic adoption unobserved."},"public_instruction":public,"conditions":["reset","information_matched_full_history","curated_correct"],"forms":forms,"schedule":schedule,"randomization":{"method":"builder-authored balanced interleave before calls","outcome_observed":False,"order":[x["attempt_id"] for x in schedule]},"budget":{"model_calls_per_attempt":1,"wall_seconds":900,"max_turns":40,"toolsets":["file"],"provider":"openai-codex","model":"gpt-5.6-sol","safe_mode":True},"eligibility":{"service":"returncode zero and usage completed without failure","environment":"read-only inputs unchanged","artifact":"artifact.json exists","no_outcome_based_retries":True,"invalid_and_service_failures_retained":True},"no_pooling_rule":"Report every shape/form/condition cell separately; never pool deterministic controls with agent trials or infer an effect from sparse cells.","non_agent_controls":{"stale_conflicting_revoked":"preflight only","deterministic_reruns":"preflight only"},"v1_preservation":{"git_tree_at_freeze":v1tree,"policy":"preserve byte-for-byte"},"frozen_components":[{"path":x,"sha256":sha(HERE/x)} for x in ["run_study.py","grade.py","README.md"]],"claim_boundaries":{"retained_state_causal_effect":False,"general_memory_capability":False,"agent_capability":False,"expert_validity":False,"professional_validity":False,"privacy":False,"collaboration":False,"safety":False,"production_fitness":False,"readiness":False,"cross_domain_generalization":False}}
out=HERE/"protocol.json"
if out.exists():raise FileExistsError(out)
out.write_text(json.dumps(p,indent=2,sort_keys=True)+"\n")
print(out,sha(out))
