#!/usr/bin/env python3
"""Freeze the prospective delayed-obligation protocol before model calls."""
from __future__ import annotations
import hashlib,json,random
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
COMPONENTS=[HERE/"README.md",HERE/"instrument/scenarios.json",HERE/"instrument/prompt-template.md",HERE/"instrument/calibration-cases.json",HERE/"run_study.py",ROOT/"pilots/configured-artifact-revision/launcher.py",ROOT/"papers/agent-benchmarks/2026-07-16-pmbench-prospective-memory-validity.md"]
def sha(p:Path)->str:return hashlib.sha256(p.read_bytes()).hexdigest()
def main()->None:
 rows=[]
 for scenario in ("vendor-disposition-form-a","segment-release-form-a"):
  for condition in ("neutral_interrupt","channel_hint","oracle_reminder"):
   token=hashlib.sha256(f"{scenario}:{condition}:1:delayed-v1".encode()).hexdigest()[:10];rows.append({"attempt_id":f"dot-{token}","scenario_id":scenario,"condition_id":condition,"repeat":1})
 random.Random(716202601).shuffle(rows)
 for i,row in enumerate(rows,1):row["execution_order"]=i
 claims={x:False for x in ["general_prospective_memory","causal_treatment_effect","agent_capability","professional_capability","expert_validity","cross_domain_generality","safety","production_fitness","deployment_readiness","population_representativeness"]}
 protocol={"schema_version":"0.1.0","protocol_id":"delayed-obligation-dual-task-v1","frozen_at":"2026-07-15T21:00:39Z","charter_decision_filter":{"objectives":["B: expertise-to-evaluation methodology","C: executable infrastructure"],"artifact":"two-shape delayed-obligation protocol, deterministic replay/grader, isolated configured attempts","uncertainty":"whether obligation timing/update failures can be separated from concurrent primary-work loss under three evidence interventions","mode":"building and validation","duplication":"new prospective pilot; frozen prior pilot evidence is referenced, not modified","scope_boundary":"two synthetic work shapes test reusable dual-task machinery, not domain or cross-domain generality","useful_completion":"zero-call canaries and planted replays pass; all six bounded attempts retained or explicitly invalidated"},"configured_system":{"model":"gpt-5.6-sol","provider":"openai-codex","toolsets":["file"],"safe_mode":True,"invocation":"fresh oneshot each of three turns","timeout_seconds_per_turn":900,"retries":0,"replacement":"none"},"schedule":{"order_seed":716202601,"rows":rows,"outcome_based_retry":"forbidden"},"held_fixed":{"turns":3,"attempts_per_cell":1,"primary_sources":"same within each shape","obligation_form":"one original, one replacement/update, one obsolete lure, one due cue","prompt_and_grader":"same except declared treatment message","budget":"three calls per attempt"},"treatments":{"neutral_interrupt":"non-answer-bearing interruption; channel access only after voluntary query","channel_hint":"names obligation channel without contents; channel access only after query","oracle_reminder":"privileged evaluator-derived current update/action reminder"},"reporting":{"no_shape_pooling":True,"descriptive_only":True,"outcomes":["encoding_retention","cue_monitoring_access","update_reconciliation","due_status_timing","action_realization","obsolete_lure_commission","primary_artifact","collateral_loss","calls_tokens_cost_latency","invalid_service_environment"]},"invalidity":{"service":"nonzero call or missing/failed usage record","environment":"failed isolation canary or input mutation","artifact":"missing/malformed turn JSON or malformed primary artifact","comparison":"shape-specific exact denominators; no effect estimate"},"claim_boundaries":claims,"frozen_components":[{"path":str(p.relative_to(ROOT)),"sha256":sha(p)} for p in COMPONENTS]}
 out=HERE/"protocol.json";out.write_text(json.dumps(protocol,indent=2,sort_keys=True)+"\n");print(json.dumps({"path":str(out.relative_to(ROOT)),"sha256":sha(out),"attempts":len(rows)},indent=2))
if __name__=="__main__":main()
