#!/usr/bin/env python3
"""Build and hash-freeze the prospective v2 protocol before any model call."""
from __future__ import annotations
import hashlib,json,random
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent
COMPONENTS=[
"pilots/evidence-request-interface-v2/README.md","pilots/evidence-request-interface-v2/v1-root-surface-audit.json","pilots/evidence-request-interface-v2/instrument/prompt-template.md","pilots/evidence-request-interface-v2/instrument/parser-policy.json","pilots/evidence-request-interface-v2/instrument/grader.py","pilots/evidence-request-interface-v2/run_study.py","pilots/evidence-acquisition-matched-agent-v1/instrument/scenarios/compliance.json","pilots/evidence-acquisition-matched-agent-v1/instrument/scenarios/analysis.json","pilots/configured-artifact-revision/launcher.py"]
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 rows=[]
 for repeat in (1,2):
  for scenario in ("vendor-disposition","segment-release"):
   for interface in ("natural_request","structured_request"):
    token=hashlib.sha256(f"{scenario}:{interface}:{repeat}:eri-v2".encode()).hexdigest()[:10];rows.append({"attempt_id":f"eri-{token}","scenario_id":scenario,"interface_id":interface,"repeat":repeat})
 random.Random(7152026).shuffle(rows)
 for i,row in enumerate(rows,1):row["execution_order"]=i
 claims={key:False for key in ["causal_inquiry_benefit","agent_capability","professional_capability","clinical_validity","compliance_validity","expert_validity","safety","production_fitness","deployment_readiness","population_representativeness","cross_domain_generality"]}
 protocol={"schema_version":"0.1.0","protocol_id":"evidence-request-interface-v2","frozen_at":"2026-07-15T16:45:55Z","charter_decision_filter":{"objectives":["B: expertise-to-evaluation methodology","C: executable infrastructure"],"artifact":"hash-pinned v1 audit and frozen 2-shape x 2-interface x 2-repeat active-only matrix","uncertainty":"whether parser-mediated surface failures change under a minimally structured request syntax","mode":"building and validation","duplication":"versions the executed v1 pilot instead of altering it or creating a parallel schema","scope_boundary":"synthetic cross-shape interface probe, not a profession or generality claim","useful_completion":"eight retained attempts or exact invalid cells, replayable decomposition, synonym and negative-control conformance"},"configured_system":{"model":"gpt-5.6-sol","provider":"openai-codex","toolsets":["file"],"safe_mode":True,"invocation":"fresh oneshot per interaction turn","max_interaction_turns":4,"timeout_seconds_per_turn":900,"retries":0,"replacement":"none"},"schedule":{"order_seed":7152026,"task_seed":"sha256(scenario:interface:repeat:eri-v2)","rows":rows,"outcome_based_retry":"forbidden"},"held_fixed":{"latent_evidence_graphs":"byte-identical v1 scenario files","public_basis":"byte-identical v1 target and public context","available_evidence_labels":"no IDs or menus exposed in either interface","budget":3,"release_delay_denial_rules":"same across interfaces","prompt":"one shared template; only request syntax block differs","grader":"same endpoint logic as v1","stopping_loss_rules":"same disclosed public rules","repeat_count":2},"treatment":{"natural_request":"original free-text shape with deterministic substring aliases","structured_request":"one exact normalized topic; no menu, IDs, availability, values, or answers exposed","malformed_or_unknown":"fail closed with no release and 0.5 budget charge"},"invalidity":{"service":"nonzero provider exit, missing usage, completed false, or failed true","environment":"failed isolation/firewall/parser canary or changed read-only inputs","artifact":"missing/malformed terminal JSON","eligibility":"paired endpoint contrast requires service, environment, cost, and artifact validity; invalid attempts remain intended"},"reporting":{"no_shape_pooling":True,"descriptive_only":True,"dimensions":["selection","expression","parser","access","terminal-citation adoption proxy","stopping","endpoint","cost"]},"claim_boundaries":claims,"frozen_components":[{"path":p,"sha256":sha(ROOT/p)} for p in COMPONENTS]}
 (HERE/"protocol.json").write_text(json.dumps(protocol,indent=2,sort_keys=True)+"\n");print(json.dumps({"protocol":str((HERE/"protocol.json").relative_to(ROOT)),"sha256":sha(HERE/"protocol.json"),"attempts":len(rows),"components":len(COMPONENTS)},indent=2))
if __name__=="__main__":main()
