#!/usr/bin/env python3
"""Build a hash-pinned post-hoc flow audit without changing frozen trials or grades."""
from __future__ import annotations
import hashlib,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2];HERE=Path(__file__).resolve().parent;EXEC=HERE/"execution"
def load(p):return json.loads(p.read_text())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def main():
 protocol=load(HERE/"protocol.json");rows=[]
 for scheduled in protocol["schedule"]["rows"]:
  path=EXEC/"attempts"/scheduled["attempt_id"]/"trial-report.json";t=load(path)
  parser_counts={x:sum(r["parser_interpretation"]["status"]==x for r in t["requests"]) for x in ("matched","ambiguous","unmatched","parser_error")}
  rows.append({"attempt_id":t["attempt_id"],"scenario_id":t["scenario_id"],"interface_id":t["interface_id"],"repeat":t["repeat"],"eligible":all(t[x] for x in ("service_valid","cost_valid","environment_valid","artifact_valid")),"trial_report_sha256":sha(path),"selection":{"request_count":len(t["requests"]),"raw_expressions":[r["raw_expression"] for r in t["requests"]]},"expression":{"syntactically_valid_count":len(t["requests"])-parser_counts["parser_error"],"malformed_count":parser_counts["parser_error"]},"parser":parser_counts,"access":{"released_ids":t["released_ids"],"statuses":[e["status"] for e in t["access_events"]]},"adoption":{"measure":"terminal citation proxy only","cited_released_ids":t["adoption"]["cited_released_ids"]},"stopping":{"reason":t["final"].get("stop_reason"),"decision":t["final"].get("decision"),"uncertainty":t["final"].get("uncertainty")},"endpoint":{"classification":t["grade"]["classification"],"quality":t["grade"]["endpoint_quality"],"decision_loss":t["grade"]["decision_loss"],"severe_omissions":t["grade"]["severe_omissions"]}})
 summary={interface:{"attempts":sum(r["interface_id"]==interface for r in rows),"requests":sum(r["selection"]["request_count"] for r in rows if r["interface_id"]==interface),"matched":sum(r["parser"]["matched"] for r in rows if r["interface_id"]==interface),"ambiguous":sum(r["parser"]["ambiguous"] for r in rows if r["interface_id"]==interface),"unmatched":sum(r["parser"]["unmatched"] for r in rows if r["interface_id"]==interface),"released":sum(len(r["access"]["released_ids"]) for r in rows if r["interface_id"]==interface),"terminal_citation_proxy":sum(len(r["adoption"]["cited_released_ids"]) for r in rows if r["interface_id"]==interface),"decision_loss":sum(r["endpoint"]["decision_loss"] for r in rows if r["interface_id"]==interface)} for interface in ("natural_request","structured_request")}
 out={"analysis_id":"evidence-request-interface-v2-flow-audit","protocol_sha256":sha(HERE/"protocol.json"),"study_report_sha256":sha(EXEC/"study-report.json"),"denominators":{"intended":8,"retained":len(rows),"eligible":sum(r["eligible"] for r in rows)},"summary":summary,"attempt_flows":rows,"interpretation":"All structured requests were syntactically valid but outside the frozen exact-synonym vocabulary; no structured evidence was released. Natural requests produced five matches, three ambiguous parses, five releases, and five terminal-citation proxies. These are exact internal surface observations, not evidence that either interface improves inquiry selection or capability.","unidentified":["semantic quality of selected evidence topics independent of parser vocabulary","counterfactual outcome under a different structured vocabulary","belief adoption beyond terminal citation","stable interface effect beyond two stochastic repeats","cross-shape, professional, safety, production, or readiness generality"],"no_rescoring":True}
 (EXEC/"flow-audit.json").write_text(json.dumps(out,indent=2,sort_keys=True)+"\n");print(json.dumps({"path":str((EXEC/"flow-audit.json").relative_to(ROOT)),"retained":len(rows),"eligible":sum(r["eligible"] for r in rows),"summary":summary},indent=2))
if __name__=="__main__":main()
